
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftMULDIVrightEXPOrightUNARYADDSUB ARGSEP EXPO IDENTIFIER LPAREN MULDIV NUMBER RANGE REFERENCE RPARENexpr : LPAREN expr RPARENexpr : expr ADDSUB exprexpr : expr MULDIV exprexpr : expr EXPO exprexpr : ADDSUB expr %prec UNARYexpr : NUMBERexpr : REFERENCEexpr : IDENTIFIERexpr : IDENTIFIER LPAREN params RPARENparams : paramparams : params ARGSEP paramparam : exprparam : REFERENCE RANGE REFERENCE'
    
_lr_action_items = {'LPAREN':([0,2,3,6,7,8,9,12,22,],[2,2,2,12,2,2,2,2,2,]),'ADDSUB':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,19,20,21,22,],[3,7,3,3,-6,-7,-8,3,3,3,7,-5,3,-2,-3,-4,-1,7,-7,-9,3,]),'NUMBER':([0,2,3,7,8,9,12,22,],[4,4,4,4,4,4,4,4,]),'REFERENCE':([0,2,3,7,8,9,12,22,23,],[5,5,5,5,5,5,20,20,25,]),'IDENTIFIER':([0,2,3,7,8,9,12,22,],[6,6,6,6,6,6,6,6,]),'$end':([1,4,5,6,11,13,14,15,16,21,],[0,-6,-7,-8,-5,-2,-3,-4,-1,-9,]),'MULDIV':([1,4,5,6,10,11,13,14,15,16,19,20,21,],[8,-6,-7,-8,8,-5,8,-3,-4,-1,8,-7,-9,]),'EXPO':([1,4,5,6,10,11,13,14,15,16,19,20,21,],[9,-6,-7,-8,9,-5,9,9,9,-1,9,-7,-9,]),'RPAREN':([4,5,6,10,11,13,14,15,16,17,18,19,20,21,24,25,],[-6,-7,-8,16,-5,-2,-3,-4,-1,21,-10,-12,-7,-9,-11,-13,]),'ARGSEP':([4,5,6,11,13,14,15,16,17,18,19,20,21,24,25,],[-6,-7,-8,-5,-2,-3,-4,-1,22,-10,-12,-7,-9,-11,-13,]),'RANGE':([20,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,2,3,7,8,9,12,22,],[1,10,11,13,14,15,19,19,]),'params':([12,],[17,]),'param':([12,22,],[18,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_lparen_expr_rparen','yacc.py',105),
  ('expr -> expr ADDSUB expr','expr',3,'p_expr_expr_addsub_expr','yacc.py',109),
  ('expr -> expr MULDIV expr','expr',3,'p_expr_expr_muldiv_expr','yacc.py',113),
  ('expr -> expr EXPO expr','expr',3,'p_expr_expr_expo_expr','yacc.py',117),
  ('expr -> ADDSUB expr','expr',2,'p_expr_addsub_expr','yacc.py',121),
  ('expr -> NUMBER','expr',1,'p_expr_number','yacc.py',125),
  ('expr -> REFERENCE','expr',1,'p_expr_reference','yacc.py',129),
  ('expr -> IDENTIFIER','expr',1,'p_expr_identifier','yacc.py',142),
  ('expr -> IDENTIFIER LPAREN params RPAREN','expr',4,'p_expr_identifier_lparen_params_rparen','yacc.py',151),
  ('params -> param','params',1,'p_params_param','yacc.py',162),
  ('params -> params ARGSEP param','params',3,'p_params_params_argsep_param','yacc.py',166),
  ('param -> expr','param',1,'p_param_expr','yacc.py',172),
  ('param -> REFERENCE RANGE REFERENCE','param',3,'p_param_reference_range_reference','yacc.py',176),
]
